AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/BlockComments:
  Enabled: false
